spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e-com-mic
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

rabbitmq:
  exchange:
    name: order.exchange
  queue:
    name: order.queue
  routing:
    key: order.tracking
    
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Ecommerce Application
    description: Spring Boot order Microservice
    version: 1.0.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
